### ISSUE TITLE
LVI-SAM算法如何适配

### ISSUE THREAD

**Issue by jerryjifjsdbf** [SJTU-ViSYS/M2DGR-plus#2]
可以提供适配文件吗

**Comment by sjtuyinjie** [comment]
你好，适配LVI-SAM需要修改代码，目前我们已经测试过，LVI-SAM能在M2DGR-Plus上正常运行，将来我们会开源代码。如果你着急的话，可以自己源代码，参照https://github.com/electech6/LVI-SAM_detailed_comments
