### ISSUE TITLE
Ground truth wrt. Lidar or IMU?

### ISSUE THREAD

**Issue by h-k8888** [SJTU-ViSYS/M2DGR-plus#3]
Thanks for the excellent work.
Can you please provide the extrinsic of the ground truth wrt. LiDAR or IMU?

**Comment by sjtuyinjie** [comment]
We ignore the extrinsic between the Lidar and the GT, because the Lidar is quite close to the GNSS RTK receiver of the GT trajectory. Besides, I have updated the calibration file here https://github.com/SJTU-ViSYS/M2DGR-plus/blob/main/calibration.txt
