### ISSUE TITLE
请问lio-sam、lvisam、a-loam、lego-loam如何配置参数文件

### ISSUE THREAD

**Issue by jerryjifjsdbf** [SJTU-ViSYS/M2DGR-plus#4]

**Comment by sjtuyinjie** [comment]
Coming soon. We are testing a lot of algorithms including A-LOAM, Lego-LOAM, LVI-SAM, R2LIVE, R3LIVE,GVINS,VINSRGBD,VINS-Mono and so on. We will release the configuration file in the future.
