### ISSUE TITLE
calibration

### ISSUE THREAD

**Issue by lian-yue0515** [SJTU-ViSYS/M2DGR-plus#7]
This is a great work, but the calibration between lidar and imu is right?
lidar2imu:
  rows: 4
  cols: 4
  dt: d
  data: [1, 0, 0, -0.13,
         0, -1, 0, 0,
         0, 0, -1, -1.03,
         0, 0, 0, 1]

**Comment by lian-yue0515** [comment]
![Screenshot from 2024-05-14 22-20-05](https://github.com/SJTU-ViSYS/M2DGR-plus/assets/63358370/3f76b411-ab04-4647-a164-0706334208f3)
When I run fastlio with this calibration, it works like this, have you tried running fastlio yet?

**Comment by sjtuyinjie** [comment]
I have tested this configure on LVI-SAM and it works fine. I recommend you use the /camera/imu instead of /imu for better performance.
